platform :ios,'7.0'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
pod 'AFNetworking', '~> 1.3.2'
pod 'RegexKitLite'
pod 'Masonry', '~> 0.6.1'
pod 'MBProgressHUDExtensions@donly', '~> 0.3'
